# Generated by Django 5.0 on 2024-01-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_user_id_listing_comment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time',
            field=models.CharField(default='Jan. 9,2024', max_length=32),
            preserve_default=False,
        ),
    ]
