# Generated by Django 5.0 on 2024-01-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, default=5.1, max_digits=7),
            preserve_default=False,
        ),
    ]
