# Generated by Django 5.0 on 2024-01-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_highest_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
