# Generated by Django 5.0 on 2024-01-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_number',
        ),
    ]
