# Generated by Django 5.0 on 2024-01-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_bid_bid_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
