# Generated by Django 5.0 on 2024-01-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_bid_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlists', to='auctions.listing'),
        ),
    ]
